// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.Models
{
    public partial class Assign_Course_To_Instructor_Track_BranchResult
    {
    }
}
