// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Procedures;

public partial class InstructorTeachCourseForTrackInBranch
{
    public string InsId { get; set; }

    public int CrsId { get; set; }

    public int TrackId { get; set; }

    public int BranchId { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Course Crs { get; set; }

    public virtual Instructor Ins { get; set; }

    public virtual Track Track { get; set; }
}