// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Models;

public partial class InstructorCourseQuestion
{
    public string InsId { get; set; }

    public int CrsId { get; set; }

    public int QuesId { get; set; }

    public virtual Course Crs { get; set; }

    public virtual Instructor Ins { get; set; }

    public virtual Question Ques { get; set; }
}