// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Procedures;

public partial class Question
{
    public int QuesId { get; set; }

    public string QuesTittle { get; set; }

    public string QuesAnswer { get; set; }

    public string QuesType { get; set; }

    public int QuesWeight { get; set; }

    public virtual ICollection<Choice> Choices { get; set; } = new List<Choice>();

    public virtual ICollection<InstructorCourseQuestion> InstructorCourseQuestions { get; set; } = new List<InstructorCourseQuestion>();

    public virtual ICollection<StudentTakeExam> StudentTakeExams { get; set; } = new List<StudentTakeExam>();

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}