// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Models;

public partial class Question
{
    public int QuesId { get; set; }

    public string QuesTittle { get; set; }

    public string QuesAnswer { get; set; }

    public string QuesType { get; set; }

    public int QuesWeight { get; set; }

    public string InsId { get; set; }

    public int CrsId { get; set; }

    public virtual Choice Choice { get; set; }

    public virtual Course Crs { get; set; }

    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();

    public virtual Instructor Ins { get; set; }

    public virtual ICollection<StudentTakeExam> StudentTakeExams { get; set; } = new List<StudentTakeExam>();
}