// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.Models
{
    public partial class Read_All_Exams_For_CourseIdResult
    {
        public int Ex_id { get; set; }
        public int Ex_grade { get; set; }
        public int Ex_duration { get; set; }
        public int crs_id { get; set; }
        public string crs_name { get; set; }
    }
}
