// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.Models
{
    public partial class Read_Incoming_Exams_For_Student_IdResult
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public int Exam_id { get; set; }
        public DateTime Exam_date { get; set; }
        public int crs_id { get; set; }
        public string crs_name { get; set; }
        public int Ex_grade { get; set; }
        public int Ex_passGrade { get; set; }
    }
}
