// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.Models
{
    public partial class Read_All_StudentsResult
    {
        public string std_id { get; set; }
        public DateOnly std_birthDate { get; set; }
        public int track_id { get; set; }
        public int branch_id { get; set; }
        public int RoleId { get; set; }
    }
}
