// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.Models
{
    public partial class Read_Track_From_Instructor_Course_BranchResult
    {
        public int track_id { get; set; }
        public string track_name { get; set; }
    }
}
