// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Models;

public partial class Student
{
    public string StdId { get; set; }

    public DateOnly StdBirthDate { get; set; }

    public int TrackId { get; set; }

    public int BranchId { get; set; }

    public int RoleId { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<StudentExamGrade> StudentExamGrades { get; set; } = new List<StudentExamGrade>();

    public virtual ICollection<StudentTakeExam> StudentTakeExams { get; set; } = new List<StudentTakeExam>();

    public virtual Track Track { get; set; }

    public virtual User User { get; set; }
}