// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Models;

public partial class TrackExam
{
    public int TrId { get; set; }

    public int BranchId { get; set; }

    public int ExamId { get; set; }

    public DateTime ExamDate { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Track Tr { get; set; }
}