// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Procedures;

public partial class TrackCourseExam
{
    public int TrId { get; set; }

    public int CrsId { get; set; }

    public int ExamId { get; set; }

    public DateOnly ExameDate { get; set; }

    public virtual Course Crs { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Track Tr { get; set; }
}