// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.Models
{
    public partial class Update_InstructorResult
    {
        public int? ErrorNumber { get; set; }
    }
}
