// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.Procedures
{
    public partial class Read_Student_Grades_By_Student_IdResult
    {
        public string std_name { get; set; }
        public string crs_name { get; set; }
        public int Exam_id { get; set; }
        public double? Grade { get; set; }
    }
}
