// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.Procedures
{
    public partial class Read_Instructor_Courses_By_Instructor_IdResult
    {
        public string crs_name { get; set; }
        public string track_name { get; set; }
        public string BranchName { get; set; }
        [Column("Number Of Students")]
        public int? NumberOfStudents { get; set; }
    }
}
