// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.Procedures
{
    public partial class Read_All_Questions_For_CourseResult
    {
        public string crs_name { get; set; }
        public string ques_tittle { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        public string ques_answer { get; set; }
        public int ques_weight { get; set; }
    }
}
