// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.Procedures
{
    public partial class Read_All_InstructorsResult
    {
        public string Ins_id { get; set; }
        public string Ins_name { get; set; }
        public string ins_password { get; set; }
        public string Ins_mobile { get; set; }
    }
}
