// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.Procedures
{
    public partial class Read_Topics_Of_CourseResult
    {
        public string crs_name { get; set; }
        public string top_name { get; set; }
    }
}
