// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.Procedures
{
    public partial class Read_Students_Data_By_Track_IdResult
    {
        public string std_id { get; set; }
        public string std_name { get; set; }
        public string std_mobile { get; set; }
        public DateOnly std_birthDate { get; set; }
        public string track_name { get; set; }
    }
}
